# Generated by Django 5.2 on 2025-04-22 18:00

from django.db import migrations

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='adminpassword'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0003_create_superuser'),
        ('Smart', '0003_teammember'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
