# Generated by Django 5.2 on 2025-04-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0003_create_superuser'),
        ('Smart', '0003_teammember'),
    ]

    operations = [
    ]
